version: '2.1'

services:
  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  ideabox:
    image: ideabox
    build: .
    environment:
      MYSQL_URI: mysql://root:root@mysql:3306/ideabox
    ports:
      - 8000:8000
      - 80:80